name: "Trigger: Nightly"


on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"


jobs:
  test-against-koji-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout koji
        run: |
          git clone --depth 1 https://pagure.io/koji.git tools/koji

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libkrb5-dev
          pip install tox

      - name: Running mypy against koji from git
        run: |
          tox -e koji-git

      - name: Running mypy against koji.hub from git
        run: |
          tox -e kojihub


# The end.
