name: "Run: Unit Tests"


on:
  workflow_call:
  workflow_dispatch:


jobs:
  pre-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libkrb5-dev
          pip install tox

      - name: Run Flake8
        run: |
          tox -e flake8

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    needs:
      - pre-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout koji
        run: |
          git clone --depth 1 https://pagure.io/koji.git tools/koji

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install libkrb5-dev
          pip install tox

      - name: Running mypy
        run: |
          tox -e mypy

      - name: Running mypy on koji.hub
        run: |
          tox -e kojihub

      - name: Running pytype
        run: |
          tox -e pytype


# The end.
